version: "3.8"

services:
  async-main-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: async-main-app
    env_file:
      - .env.example
      - .env
    network_mode: "host"
    volumes:
      - ./config.json:/app/config.json:ro
      - ./models:/app/models
      - ./conversations:/app/conversations
    stdin_open: true
    tty: true
    restart: unless-stopped
