version: "3.8"

services:
  async-main-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: async-main-app
    env_file:
      - .env
    network_mode: "host"
    volumes:
      - ./main.py:/app/main.py:ro
      - ./discord_client.py:/app/discord_client.py:ro
      - ./irc_client.py:/app/irc_client.py:ro
      - ./terminal.py:/app/terminal.py:ro
      - ./supervisor.py:/app/supervisor.py:ro
      - ./config.json:/app/config.json:ro
    restart: unless-stopped
